security:
    password_hashers:
        App\Entity\Doctors:
            algorithm: auto

    providers:
        doctor_provider:
            entity:
                class: App\Entity\Doctors
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password

        api:
            pattern: ^/api
            stateless: true


    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: PUBLIC_ACCESS }
